name: GitHub Pages

on:
  push:
    branches:
      - main  # 每次 push 到 main 分支都会触发部署

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true      # 获取 themes 子模块
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'
          extended: true        # 使用 Hugo 扩展版

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.STARDEWBLOG }}
          external_repository: Xinlu-Y/Xinlu-Y.github.io
          publish_dir: ./public
          publish_branch: main
          # cname: yourdomain.com  # 如果你有绑定自定义域名就写，没有就注释掉
